### PR TITLE
Completed Project Layout

### PR DESCRIPTION
**Pull request by Kyle-Law**
A responsive website clone of `thenextweb.com/` with HTML and CSS. Alignments have to be done with Floats, Flexbox, or Grid. Appropriate media queries have been applied and it's fully responsive across devices. 
Looking forward to TSEs reviews and recommendations :)

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!
Here are changes you need to implement before this project can be approved:
#### Navigation bar
##### Tablet version:
* [x] TWN logo should be at the leftmost part ([link to page](https://thenextweb.com/)):
image
 Original:
image
##### Mobile version:
* [x] Navigation and sub-navigation row should change to a hamburger (bars) icon at the rightmost part (next to seach icon) ([link to page](https://thenextweb.com/))
image
 Original:
image
#### Top 3 articles section
##### Large version:
* [x] It should contain TWN logo at the top left corner of the row ([link to page](https://thenextweb.com/)) :
image
 Original:
image
#### Latest news section
##### Tablet version:
* [x] It should align 3 articles per row ([link to page](https://thenextweb.com/))

#### Latest Funding section
##### Tablet version:
* [x] It should align 3 articles per row ([link to page](https://thenextweb.com/))
##### Mobile version:
* [x] It should look more like original:
image
 Original:
image

#### Latest deals section
##### Tablet version
* [x] It should align 3 deals per row ([link to page](https://thenextweb.com/))

#### Footer
##### Mobile version
* [x] Footer needs fixing:
image

 Original:
image


### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Kyle-Law** [comment]
Thank @pelzolga123 for reviewing our project! Your recommendations have been implemented and updated on the latest live-link:

- TNW logo was added at the leftmost part for sizes below 1024px
- Navigation and sub-navigation row 'change' to a hamburger (bars) icon for sizes below 768px
- A hypothetical TNW logo was added at the top-left part of the first main article and disappeared for sizes below 1024px
- Latest-fundings section headers alignment fixed for sizes below 1024px.
- Footers logo size decreased to prevent overflow issues for screen-sizes below 400px
- For the latest-news, latest-fundings, and latest-deals section, we used `grid-template-columns: repeat(auto-fit, 294px);` to automatically sizing them among 768px - desktop sizes.

The above stated our changes. Looking forward to another code review by TSEs :)

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Quemé P. (TSE) 

### Hello @Kyle-Law  and @jaspreet-singh-sahota :wave: :balloon:

### Congratulations! your project is looking better and better :raised_hands:  thank you for doing the changes requested by the previous reviewer :medal_sports: there is still some work to do :muscle: 

**navbar**

- [ ] README link doesn't exist in the original

**navbar (768px screen)**

- [x] the links About, Team, Advertise, Jobs and Contact shouldn't be displayed in this screen size

- Yours
image

- Original
image

**Latest news (768px screen)**

- [x] the articles are splitting into 2 columns when they should be in 3 columns like the original

- Yours

image

- Original

image

**Latest news (1024px screen)**

- [x] the articles are splitting into 3 columns when they should be in 4 columns like the original

- Yours

image

- Original

image

**Latest fundings rounds (small screen)**

- [x] The menu has **See more** on the top **Get updates by email** in the middle and **Add info** in the bottom

- Yours

image

- Original

image

- [x] The articles should take the whole screen width or at least 90% of it

- [x] you are displaying 4 articles when only 3 articles should be displayed in this screen size

- Yours

image

- Original

image


**Latest fundings rounds (769px screen)**

- [x] The menu should have a particular order: See more | Get updates by email | Add info

- Yours

image

- Original

image

- [x] the articles are splitting into 2 columns when they should be in 3 columns like the original and is showing all the articles when it should hide one of them

- Yours

image

- Original

image

**Latest fundings rounds (1025px screen)**

- [x] The articles are still splitting into 3 columns when they should all fit in the screen (4 columns)

- Yours

image

- Original

image

**Categories (Apps, GERA, Tech, etc) section (small screen)**

- [x] Check the order of the articles at this size (Apps should be the first one to be displayed not Distract)

- [x] The articles should take the whole screen width or at least 90% of it

- Yours

image

- Original

image

**Categories (Apps, GERA, Tech, etc) section (1024px screen)**

- [x] the articles are splitting into 2 columns when they should be in 3 columns like the original

- Yours

image

- Original

image

**Latest Deals (small screen)**

- [x] the "See all Deals" link should be at the rightmost part of the page

- Yours

image

- Original 

image

**Latest Deals (768px screen)**

- [x] the articles are splitting into 2 columns when they should be in 3 columns like the original
- [x] the "See all Deals" link should be at the rightmost part of the page

- Yours

image

- Original

image

**Latest Deals (768px screen)**

- [x] the articles are splitting into 3 columns when they should be in 4 columns like the original

- Yours

image

- Original

image

**Footer**

- [ ] the links below the social icons should be in all caps

- [ ] there is not a "Team" link

- [ ] the "EVENTS" link is missing

- [ ] the text in the bottom should be centered in 3 rows for the small screen

- Yours
image


- Original

image

### That would be it, Team! 

### Please :pray:  make these changes and submit back for a code review when you are done :rocket: 

Happy coding! :woman_technologist: 

STATUS OF THE PROJECT: REQUESTED CHANGES :traffic_light:

**Comment by Kyle-Law** [comment]
Thank @euqueme for reviewing our project! Your recommendations have been applied as listed below: 

Header section:
- About `div` removed for screen sizes below 1024px.

Latest-news section:
- Fix 2cols to 3cols for screen sizes below 1024px.
- Occupy box width to screen size given.

Latest-fundings section:
- Fix 2cols to 3cols for screen sizes below 1024px.
- Occupy box width to screen size given.
- Fix latest-fundings section alignment for screen size between 768px and 1024px.
- 'See More' comes before 'Add info' for the fundings-section.

Other-articles section:
- Articles sequences fixed.
- Occupy box width to screen size given.

Latest-deals section:
- 'See All Deals' realigned for screen sizes below 1024px.

Footer section:
- Footer font capitalized and realigned for smaller screen sizes.
- Footer text changed.

Others:
- README live link updated.
- HTML and CSS Validated.

Looking forward to another review by TSEs! :)

**Review by rOluochKe — APPROVED** [review]
Hello @Kyle-Law and @jaspreet-singh-sahota 

### You have done an amazing job, you project looks much better now :clap:
- Having reviewed your project, I, therefore, Approve of it :star:
- You can merge and submit project completion from your dashboard.

### I wish you all the best, in your next project. Happy coding!

**Comment by Kyle-Law** [comment]
Thanks @rOluochKe , @euqueme , and @pelzolga123 for reviewing our project! The branch shall be merged :)

**Pull request merged**
